# Generated by Django 3.1.4 on 2021-01-06 20:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_usernewsrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='readers',
            field=models.ManyToManyField(through='news.UserNewsRelation', to=settings.AUTH_USER_MODEL),
        ),
    ]
